# Generated by Django 5.2.8 on 2025-11-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendancesession_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='gender',
        ),
    ]
