# Generated by Django 5.2.8 on 2025-11-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_room_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dormitory'),
        ),
    ]
