# Generated by Django 5.2.8 on 2025-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_admin_comment_alter_student_dormitory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin tomonidan qoldirilgan izoh', null=True),
        ),
    ]
