# Generated by Django 5.2.8 on 2025-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Xona biriktirilgandan keyin true bo'ladi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Qabul qilindi', 'Qabul qilindi'), ('Joylashdi', 'Joylashdi')], default='Qabul qilindi', max_length=120),
        ),
    ]
