# Generated by Django 5.2.8 on 2026-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_room_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
