# Generated by Django 5.2.8 on 2026-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dormitory_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='phone_numer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
